### PR TITLE
SLING-8419 refactor method to serialize OSGi configs as JSON

### PR DESCRIPTION
**Pull request by kwin**
This allows reuse in the OSGi installer

### CODE REVIEW

**Review by cziegeler — COMMENTED** [review]
The change by itself looks good to me; but do we really need a public api taking a JsonGenerator? I would assume that we need a public api which gets a writer and a Dictionary passed

**Comment by kwin** [comment]
> The change by itself looks good to me; but do we really need a public api taking a JsonGenerator? I would assume that we need a public api which gets a writer and a Dictionary passed

Having a JsonGenerator as argument allows to e.g. emit without pretty printing. Also the writer approach would require a real instance of the object (instead of a simple static method) as the factory for JsonGenerator is only available there. I definitely see your point of using simpler classes for APIs but I also see some drawbacks here...

**Comment by cziegeler** [comment]
Without such an API, users of the API need to fiddle around with JSON - which I think they shouldn't. They just want to write out a configuration

**Comment by kwin** [comment]
I will change the API and also make sure the writer is not being closed.

**Review by cziegeler — APPROVED** [review]

**Pull request merged**
